// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABIlo36ZehJbxxzrlCeC44OyKCWo6HgIg',
    appId: '1:343567827965:web:622a3c8a5e70927398cf94',
    messagingSenderId: '343567827965',
    projectId: 'driplix-9ce7a',
    authDomain: 'driplix-9ce7a.firebaseapp.com',
    storageBucket: 'driplix-9ce7a.firebasestorage.app',
    measurementId: 'G-PJS78P0FZE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Pa9gDP8lzZEHZNxWo6imwuY1ZBqgHaY',
    appId: '1:343567827965:ios:554183a86f7adf9898cf94',
    messagingSenderId: '343567827965',
    projectId: 'driplix-9ce7a',
    storageBucket: 'driplix-9ce7a.firebasestorage.app',
    iosBundleId: 'com.driplix.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Pa9gDP8lzZEHZNxWo6imwuY1ZBqgHaY',
    appId: '1:343567827965:ios:554183a86f7adf9898cf94',
    messagingSenderId: '343567827965',
    projectId: 'driplix-9ce7a',
    storageBucket: 'driplix-9ce7a.firebasestorage.app',
    iosBundleId: 'com.driplix.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsDPecTSoz4DYp5X9bOHgduuzMN6RssJM',
    appId: '1:343567827965:android:83cd86d62ab34b9798cf94',
    messagingSenderId: '343567827965',
    projectId: 'driplix-9ce7a',
    storageBucket: 'driplix-9ce7a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABIlo36ZehJbxxzrlCeC44OyKCWo6HgIg',
    appId: '1:343567827965:web:73c03ad3bd93b9ce98cf94',
    messagingSenderId: '343567827965',
    projectId: 'driplix-9ce7a',
    authDomain: 'driplix-9ce7a.firebaseapp.com',
    storageBucket: 'driplix-9ce7a.firebasestorage.app',
    measurementId: 'G-SLX2BXSLHD',
  );

}